### PR TITLE
P2PW-1432 - make secretWords autoResizable

### PR DESCRIPTION
**Pull request by kabramovp2p**

### CODE REVIEW

**Review by gslevinkov — APPROVED** [review]

**Review by 1sakov — APPROVED** [review]

**Comment by gslevinkov** [comment]
wrong commit naming

**Comment by kabramovp2p** [comment]
> wrong commit naming

waaaat?

**Comment by kabramovp2p** [comment]
> > wrong commit naming
> 
> waaaat?

ohh i think I got it

secret words made autoResizable 

here what it should be... I presume

**Comment by gslevinkov** [comment]
nah nah nah
im not so bad to comment on typos and grammar :)
What I meant is:
P2PW-1432 make secret words autoResizable - wrong
P2PW-1432 **-** make secret words autoResizable - ok!

**Pull request merged**
