### PR TITLE
PWN-4924 - Buy details screen changes

### PR DESCRIPTION
**Pull request by 1sakov**
## Jira Ticket

https://p2pvalidator.atlassian.net/browse/PWN-4924

## Description of Work

Added error state for buy details bottom sheet

## Screenshots (Optional)

Screenshot_20220907_211119

### CODE REVIEW

**Review by kuznetsov — APPROVED** [review]
Image could be exported as svg

**Comment by kabramovp2p** [comment]
yes SVG or please convert PNG to webp

**Comment by kabramovp2p** [comment]
otherwise looks good

**Review by kabramovp2p — APPROVED** [review]

**Comment by kabramovp2p** [comment]
also screenshot is good practice

**Comment by 1sakov** [comment]
> also screenshot is good practice

@kuznetsov @kabramovp2p hey guys, I couldn't get the entry point since your MR is not merged yet. 
Please feel free to use this bottom sheet once you are ready

**Pull request merged**
