### PR TITLE
PWN-3049 - Disable skip for ReserveUsernameFragment opened from Home

### PR DESCRIPTION
**Pull request by kuznetsov**
## Jira Ticket

https://p2pvalidator.atlassian.net/browse/PWN-3049

## Description of Work

Remove *You can also skip this step and reserve a username later* text in Reserve Username in case of opening it from Home

### CODE REVIEW

**Comment by gslevinkov** [comment]
wrong commit naming, sry

**Review by 1sakov — APPROVED** [review]

**Comment by kuznetsov** [comment]
> wrong commit naming and no assignee

What's wrong with commit name?

**Comment by gslevinkov** [comment]
> > wrong commit naming and no assignee
> 
> What's wrong with commit name?

we don't use square brackets for task name. 
` [PWN-3049] - Disable skip for ReserveUsernameFragment opened from Home`
to
`PWN-3049 - Disable skip for ReserveUsernameFragment opened from Home`

**Comment by kuznetsov** [comment]
Sure, thanks

**Review by kabramovp2p — APPROVED** [review]

**Pull request merged**
